package ru.memearena.analytics.domain;
public enum ProductEventType { APP_OPENED, ONBOARDING_COMPLETED, BATTLE_OPENED, VOTE_COMPLETED, TOP_OPENED, MEME_UPLOAD_COMPLETED, PROFILE_OPENED, SCOUT_PREDICTIONS_OPENED, TOURNAMENT_OPENED, TOURNAMENT_VOTE_COMPLETED }
