name: meme_arena
description: Android MVP client for Meme Arena
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
