package ru.memearena.security;

import jakarta.servlet.*; import jakarta.servlet.http.*; import org.springframework.http.HttpStatus; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Component; import org.springframework.web.filter.OncePerRequestFilter; import ru.memearena.error.*; import ru.memearena.session.infrastructure.UserSessionRepository; import ru.memearena.user.infrastructure.UserProfileRepository; import com.fasterxml.jackson.databind.ObjectMapper; import java.io.IOException; import java.time.*; import java.util.*;

@Component public class BearerTokenAuthenticationFilter extends OncePerRequestFilter{
 private final TokenService tokens; private final UserSessionRepository sessions; private final UserProfileRepository users; private final Clock clock; private final ObjectMapper mapper; private final String adminToken;
 public BearerTokenAuthenticationFilter(TokenService tokens,UserSessionRepository sessions,UserProfileRepository users,Clock clock,ObjectMapper mapper,org.springframework.core.env.Environment env){this.tokens=tokens;this.sessions=sessions;this.users=users;this.clock=clock;this.mapper=mapper;this.adminToken=env.getProperty("MEME_ARENA_ADMIN_TOKEN",env.getProperty("app.admin-token",env.getProperty("meme-arena.admin-token","")));}
 protected void doFilterInternal(HttpServletRequest req,HttpServletResponse res,FilterChain chain)throws ServletException,IOException{String h=req.getHeader("Authorization"); if(h!=null&&h.startsWith("Bearer ")){String raw=h.substring(7); if(req.getRequestURI().startsWith("/api/v1/admin/")){ if(adminToken!=null&&!adminToken.isBlank()&&tokens.constantEquals(raw,adminToken)) SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(new AdminPrincipal(),null,List.of(new SimpleGrantedAuthority("ROLE_ADMIN")))); else {write(res,req,HttpStatus.FORBIDDEN,ErrorCode.ACCESS_DENIED,"Invalid admin token"); return;} } else {var hash=tokens.sha256(raw); var s=sessions.findByTokenHash(hash); if(s.isEmpty()){write(res,req,HttpStatus.UNAUTHORIZED,ErrorCode.INVALID_ACCESS_TOKEN,"Invalid access token");return;} var session=s.get(); var now=Instant.now(clock); if(session.revoked()){write(res,req,HttpStatus.UNAUTHORIZED,ErrorCode.ACCESS_TOKEN_REVOKED,"Access token revoked");return;} if(session.expired(now)){write(res,req,HttpStatus.UNAUTHORIZED,ErrorCode.ACCESS_TOKEN_EXPIRED,"Access token expired");return;} var u=users.findById(session.getUserId()); if(u.isEmpty()){write(res,req,HttpStatus.UNAUTHORIZED,ErrorCode.INVALID_ACCESS_TOKEN,"Invalid access token");return;} session.touch(now); sessions.save(session); SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(new AuthenticatedUserPrincipal(u.get().getId(),u.get().getNickname(),session.getId()),null,List.of(new SimpleGrantedAuthority("ROLE_USER")))); }} chain.doFilter(req,res); }
 private void write(HttpServletResponse res,HttpServletRequest req,HttpStatus st,ErrorCode c,String m)throws IOException{res.setStatus(st.value());res.setContentType("application/json");mapper.writeValue(res.getOutputStream(),new ApiError(c.name(),m,Instant.now(clock),req.getRequestURI(),List.of()));}
}
