import 'dart:io';import 'package:dio/dio.dart';import '../core/errors/app_error.dart';import '../core/network/session_store.dart';import 'models.dart';
class ApiRepository{ApiRepository(this.dio,this.store);final Dio dio;final SessionStore store;Future<T> _wrap<T>(Future<T> Function() f)async{try{return await f();}on DioException catch(e){throw AppError.fromDio(e);}}
Future<UserProfile> createGuest(String nickname)=>_wrap(()async{final installationId=await store.installationId();final data=((await dio.post('/api/v1/users/guest',data:{'nickname':nickname,'installationId':installationId})).data as Map).cast<String,dynamic>();final user=UserProfile.fromJson((data['user'] as Map).cast());await store.saveUser(userId:user.id,nickname:user.nickname,accessToken:data['accessToken'].toString());return user;});
Future<UserProfile> getProfile([String? ignored])=>_wrap(()async=>UserProfile.fromJson(((await dio.get('/api/v1/users/me')).data as Map).cast()));
Future<Battle?> getNextBattle()=>_wrap(()async{final r=await dio.get('/api/v1/battles/next',options:Options(validateStatus:(s)=>s==200||s==204));return r.statusCode==204?null:Battle.fromJson((r.data as Map).cast());});
Future<VoteResult> submitVote(Battle b,String winnerMemeId)=>_wrap(()async=>VoteResult.fromJson(((await dio.post('/api/v1/votes',data:{'leftMemeId':b.left.id,'rightMemeId':b.right.id,'winnerMemeId':winnerMemeId})).data as Map).cast()));
Future<List<MemeItem>> getTop({String period='ALL_TIME',int limit=20})=>_wrap(()async=>(((await dio.get('/api/v1/memes/top',queryParameters:{'period':period,'limit':limit})).data['items'])as List).map((e)=>MemeItem.fromJson((e as Map).cast())).toList());
Future<PredictionPage> getPredictions({String? status,int page=0,int size=20})=>_wrap(()async=>PredictionPage.fromJson(((await dio.get('/api/v1/users/me/predictions',queryParameters:{if(status!=null)'status':status,'page':page,'size':size})).data as Map).cast()));
Future<ScoutLeaderboard> getScoutLeaderboard({String period='ALL_TIME',int limit=50})=>_wrap(()async=>ScoutLeaderboard.fromJson(((await dio.get('/api/v1/users/leaderboard',queryParameters:{'period':period,'limit':limit})).data as Map).cast()));
Future<MediaUpload> uploadImage(File file)=>_wrap(()async{final fd=FormData.fromMap({'file':await MultipartFile.fromFile(file.path,filename:file.path.split('/').last)});return MediaUpload.fromJson(((await dio.post('/api/v1/media/images',data:fd)).data as Map).cast());});
Future<void> createMeme({required String title,String? imageUrl,String? mediaAssetId,String? sourceUrl})=>_wrap(()async{await dio.post('/api/v1/memes',data:{'title':title,'mediaAssetId':mediaAssetId,'imageUrl':imageUrl,'sourceUrl':sourceUrl?.isEmpty==true?null:sourceUrl});});
Future<void> logout()=>_wrap(()async{await dio.post('/api/v1/users/me/logout');await store.clearUserSession();});}
