import 'dart:io';import 'package:dio/dio.dart';import '../core/errors/app_error.dart';import 'models.dart';
class ApiRepository{ApiRepository(this.dio,this.userIdProvider);final Dio dio;final Future<String?> Function() userIdProvider;Future<T> _wrap<T>(Future<T> Function() f)async{try{return await f();}on DioException catch(e){throw AppError.fromDio(e);}}
Future<UserProfile> createGuest(String nickname)=>_wrap(()async=>UserProfile.fromJson(((await dio.post('/api/v1/users/guest',data:{'nickname':nickname})).data as Map).cast()));
Future<UserProfile> getProfile(String userId)=>_wrap(()async=>UserProfile.fromJson(((await dio.get('/api/v1/users/me',queryParameters:{'userId':userId})).data as Map).cast()));
Future<Battle?> getNextBattle() => _wrap(()async{final uid=await userIdProvider();final r=await dio.get('/api/v1/battles/next',queryParameters:{'userId':uid},options:Options(validateStatus:(s)=>s==200||s==204));return r.statusCode==204?null:Battle.fromJson((r.data as Map).cast());});
Future<VoteResult> submitVote(Battle b,String winnerMemeId)=>_wrap(()async{final r=await dio.post('/api/v1/votes',data:{'userId':await userIdProvider(),'leftMemeId':b.left.id,'rightMemeId':b.right.id,'winnerMemeId':winnerMemeId});return VoteResult.fromJson((r.data as Map).cast());});
Future<List<PredictionItem>> getPredictions({String? status,int page=0,int size=20})=>_wrap(()async=>(((await dio.get('/api/v1/users/me/predictions',queryParameters:{'status':status,'page':page,'size':size})).data['items'])as List).map((e)=>PredictionItem.fromJson((e as Map).cast())).toList());
Future<List<ScoutLeaderboardItem>> getScoutLeaderboard({String period='ALL_TIME',int limit=50})=>_wrap(()async=>(((await dio.get('/api/v1/users/leaderboard',queryParameters:{'period':period,'limit':limit})).data['items'])as List).map((e)=>ScoutLeaderboardItem.fromJson((e as Map).cast())).toList());
Future<List<MemeItem>> getTop({String period='ALL_TIME',int limit=20})=>_wrap(()async=>(((await dio.get('/api/v1/memes/top',queryParameters:{'period':period,'limit':limit})).data['items'])as List).map((e)=>MemeItem.fromJson((e as Map).cast())).toList());
Future<MediaUpload> uploadImage(File file)=>_wrap(()async{final fd=FormData.fromMap({'userId':await userIdProvider(),'file':await MultipartFile.fromFile(file.path,filename:file.path.split('/').last)});return MediaUpload.fromJson(((await dio.post('/api/v1/media/images',data:fd)).data as Map).cast());});
Future<void> createMeme({required String title,String? imageUrl,String? mediaAssetId,String? sourceUrl})=>_wrap(()async{await dio.post('/api/v1/memes',data:{'uploaderId':await userIdProvider(),'title':title,'mediaAssetId':mediaAssetId,'imageUrl':imageUrl,'sourceUrl':sourceUrl?.isEmpty==true?null:sourceUrl});});}
