class ScoutStats{ScoutStats({required this.points,required this.rank,required this.predictionsCount,required this.successfulPredictions,required this.failedPredictions,required this.expiredPredictions,this.accuracy,required this.currentSuccessStreak,required this.bestSuccessStreak});final int points,predictionsCount,successfulPredictions,failedPredictions,expiredPredictions,currentSuccessStreak,bestSuccessStreak;final String rank;final double? accuracy;factory ScoutStats.fromJson(Map<String,Object?> j)=>ScoutStats(points:((j['points']??0)as num).toInt(),rank:(j['rank']??'OBSERVER').toString(),predictionsCount:((j['predictionsCount']??0)as num).toInt(),successfulPredictions:((j['successfulPredictions']??0)as num).toInt(),failedPredictions:((j['failedPredictions']??0)as num).toInt(),expiredPredictions:((j['expiredPredictions']??0)as num).toInt(),accuracy:(j['accuracy'] as num?)?.toDouble(),currentSuccessStreak:((j['currentSuccessStreak']??0)as num).toInt(),bestSuccessStreak:((j['bestSuccessStreak']??0)as num).toInt());}
class Achievement{Achievement(this.code,this.title,this.description,this.unlockedAt);final String code,title,description,unlockedAt;factory Achievement.fromJson(Map<String,Object?> j)=>Achievement(j['code'].toString(),j['title'].toString(),j['description'].toString(),j['unlockedAt'].toString());}
class UserProfile{UserProfile({required this.id,required this.nickname,required this.votesCount,required this.submittedMemesCount,required this.status,required this.scout,required this.achievements,this.createdAt});final String id,nickname,status;final int votesCount,submittedMemesCount;final String? createdAt;final ScoutStats scout;final List<Achievement> achievements;factory UserProfile.fromJson(Map<String,Object?> j)=>UserProfile(id:j['id'].toString(),nickname:j['nickname'].toString(),votesCount:(j['votesCount'] as num).toInt(),submittedMemesCount:(j['submittedMemesCount'] as num).toInt(),status:(j['rank']??j['status']??'OBSERVER').toString(),scout:ScoutStats.fromJson((j['scout'] as Map?)?.cast<String,Object?>()??{}),achievements:((j['achievements'] as List?)??[]).cast<Map<String,Object?>>().map(Achievement.fromJson).toList(),createdAt:j['createdAt']?.toString());}
class MemeItem{MemeItem({required this.id,required this.title,required this.imageUrl,required this.rating,this.wins=0,this.losses=0,this.position});final String id,title,imageUrl;final int rating;final int wins,losses;final int? position;factory MemeItem.fromJson(Map<String,Object?> j)=>MemeItem(id:(j['id']??j['memeId']).toString(),title:j['title'].toString(),imageUrl:(j['contentUrl']??j['imageUrl']??'').toString(),rating:((j['rating']??0) as num).toInt(),wins:((j['wins']??0)as num).toInt(),losses:((j['losses']??0)as num).toInt(),position:j['position']==null?null:(j['position']as num).toInt());}
class Battle{Battle(this.battleId,this.left,this.right);final String battleId;final MemeItem left,right;factory Battle.fromJson(Map<String,Object?> j)=>Battle(j['battleId'].toString(),MemeItem.fromJson(j['left'] as Map<String,Object?>),MemeItem.fromJson(j['right'] as Map<String,Object?>));}
class PredictionItem{PredictionItem(this.id,this.status,this.meme,this.pointsAwarded);final String id,status;final MemeItem meme;final int pointsAwarded;factory PredictionItem.fromJson(Map<String,Object?> j)=>PredictionItem(j['id'].toString(),j['status'].toString(),MemeItem.fromJson(j['meme'] as Map<String,Object?>),((j['pointsAwarded']??0)as num).toInt());}
class ScoutLeaderboardItem{ScoutLeaderboardItem(this.position,this.userId,this.nickname,this.rank,this.scoutPoints,this.accuracy);final int position,scoutPoints;final String userId,nickname,rank;final double? accuracy;factory ScoutLeaderboardItem.fromJson(Map<String,Object?> j)=>ScoutLeaderboardItem((j['position']as num).toInt(),j['userId'].toString(),j['nickname'].toString(),j['rank'].toString(),(j['scoutPoints']as num).toInt(),(j['accuracy'] as num?)?.toDouble());}
String statusLabel(String s)=>rankLabel(s);String rankLabel(String s)=>switch(s){'OBSERVER'=>'Наблюдатель','SCOUT'=>'Мемный скаут','TREND_HUNTER'=>'Охотник за трендами','MEME_ORACLE'=>'Мемный оракул','NEWBIE'=>'Новичок','MEME_LORD'=>'Мемный лорд',_=>s};String predictionStatusLabel(String s)=>switch(s){'PENDING'=>'Ожидают','SUCCESS'=>'Успешные','FAILED'=>'Неудачные','EXPIRED'=>'Истёкшие',_=>s};String periodCode(int i)=>['DAY','WEEK','ALL_TIME'][i];String? validateNickname(String v){final t=v.trim();if(t.length<3||t.length>30)return 'Ник должен быть от 3 до 30 символов';if(!RegExp(r'^[A-Za-zА-Яа-я0-9_ -]+$').hasMatch(t))return 'Используйте буквы, цифры, пробел, _ или -';return null;}

String accuracyLabel(double? v)=>v==null?'—':'${(v*100).round()}%';
