package ru.memearena.error;
public enum ErrorCode { USER_NOT_FOUND, MEME_NOT_FOUND, NICKNAME_ALREADY_EXISTS, INVALID_WINNER, INVALID_BATTLE_PAIR, PAIR_ALREADY_VOTED, MEME_NOT_AVAILABLE, VALIDATION_ERROR, INTERNAL_ERROR }
