import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:image_picker/image_picker.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'dart:io';
import '../core/network/dio_provider.dart';import '../features/api_repository.dart';import '../features/models.dart';
final repoProvider=Provider((ref)=>ApiRepository(ref.watch(dioProvider)));
final sessionProvider=AsyncNotifierProvider<Session,String?>(Session.new);
class Session extends AsyncNotifier<String?>{String? nickname;@override Future<String?> build()async{final p=await SharedPreferences.getInstance();final id=p.getString('userId');nickname=p.getString('nickname');if(id!=null){try{await ref.read(repoProvider).profile(id);return id;}catch(_){await p.clear();}}return null;}Future<void> start(String n)async{state=const AsyncLoading();state=await AsyncValue.guard(()async{final u=await ref.read(repoProvider).createGuest(n.trim());final p=await SharedPreferences.getInstance();await p.setString('userId',u.id);await p.setString('nickname',u.nickname);nickname=u.nickname;return u.id;});}Future<void> logout()async{final p=await SharedPreferences.getInstance();await p.remove('userId');await p.remove('nickname');state=const AsyncData(null);}}
class AppRoot extends ConsumerWidget{const AppRoot({super.key});@override Widget build(c,ref){final s=ref.watch(sessionProvider);return s.when(loading:()=>const Scaffold(body:Center(child:CircularProgressIndicator())),error:(e,_)=>Onboarding(error:e.toString()),data:(id)=>id==null?const Onboarding():const Home());}}
class Onboarding extends ConsumerStatefulWidget{const Onboarding({super.key,this.error});final String? error;@override ConsumerState<Onboarding> createState()=>_OnboardingState();}class _OnboardingState extends ConsumerState<Onboarding>{final c=TextEditingController();String? err;@override Widget build(x){final loading=ref.watch(sessionProvider).isLoading;return Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(children:[Text('Meme Arena',style:Theme.of(context).textTheme.displaySmall),const SizedBox(height:12),const Text('Выбирай лучшие мемы и повышай свой мемный статус',textAlign:TextAlign.center),const SizedBox(height:24),TextField(controller:c,decoration:InputDecoration(labelText:'Ник',errorText:err??widget.error,border:const OutlineInputBorder())),const SizedBox(height:16),FilledButton(onPressed:loading?null:(){final e=validateNickname(c.text);setState(()=>err=e);if(e==null)ref.read(sessionProvider.notifier).start(c.text);},child:Text(loading?'Загрузка...':'Начать'))]))));}}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}class _HomeState extends State<Home>{int i=0;@override Widget build(c){final pages=[const BattleScreen(),const TopScreen(),const UploadScreen(),const ProfileScreen()];return Scaffold(body:pages[i],bottomNavigationBar:NavigationBar(selectedIndex:i,onDestinationSelected:(v)=>setState(()=>i=v),destinations:const [NavigationDestination(icon:Icon(Icons.sports_mma),label:'Битва'),NavigationDestination(icon:Icon(Icons.leaderboard),label:'Топ'),NavigationDestination(icon:Icon(Icons.upload),label:'Загрузить'),NavigationDestination(icon:Icon(Icons.person),label:'Профиль')],));}}
final battleProvider=FutureProvider.autoDispose((ref)async{final id=ref.watch(sessionProvider).value!;return ref.watch(repoProvider).battle(id);});
class BattleScreen extends ConsumerStatefulWidget{const BattleScreen({super.key});@override ConsumerState<BattleScreen> createState()=>_BattleScreenState();}class _BattleScreenState extends ConsumerState<BattleScreen>{bool voting=false;Future<void> vote(Battle b,String w)async{if(voting)return;setState(()=>voting=true);final id=ref.read(sessionProvider).value!;try{final r=await ref.read(repoProvider).vote(id,b,w);final win=r['winner'] as Map;final delta=(win['ratingAfter'] as int)-(win['ratingBefore'] as int);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Голос учтён: +$delta рейтинга победителю')));ref.invalidate(battleProvider);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>voting=false);}}@override Widget build(c){final b=ref.watch(battleProvider);return SafeArea(child:b.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text('Ошибка: $e'),FilledButton(onPressed:()=>ref.invalidate(battleProvider),child:const Text('Повторить'))])),data:(v)=>v==null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Ты проголосовал за все доступные пары'),FilledButton(onPressed:()=>ref.invalidate(battleProvider),child:const Text('Обновить'))])):ListView(padding:const EdgeInsets.all(16),children:[Text('Какой мем смешнее?',style:Theme.of(context).textTheme.headlineMedium,textAlign:TextAlign.center),MemeCard(m:v.left,onTap:()=>vote(v,v.left.id),disabled:voting),const Center(child:Text('VS')),MemeCard(m:v.right,onTap:()=>vote(v,v.right.id),disabled:voting)])));}}
class MemeCard extends StatelessWidget{const MemeCard({super.key,required this.m,this.onTap,this.disabled=false});final MemeItem m;final VoidCallback? onTap;final bool disabled;@override Widget build(c)=>Card(clipBehavior:Clip.antiAlias,child:InkWell(onTap:disabled?null:onTap,child:Column(children:[AspectRatio(aspectRatio:4/3,child:CachedNetworkImage(imageUrl:m.imageUrl,fit:BoxFit.cover,placeholder:(_,__)=>const Center(child:CircularProgressIndicator()),errorWidget:(_,__,___)=>const Center(child:Icon(Icons.broken_image,size:48)))),ListTile(title:Text(m.title),subtitle:Text('Рейтинг ${m.rating}'))])));}
final topProvider=FutureProvider.family<List<MemeItem>,String>((ref,p)=>ref.watch(repoProvider).top(p));
class TopScreen extends ConsumerStatefulWidget{const TopScreen({super.key});@override ConsumerState<TopScreen> createState()=>_TopScreenState();}class _TopScreenState extends ConsumerState<TopScreen>{int i=0;@override Widget build(c){final p=periodCode(i);final a=ref.watch(topProvider(p));return SafeArea(child:Column(children:[SegmentedButton<int>(segments:const [ButtonSegment(value:0,label:Text('День')),ButtonSegment(value:1,label:Text('Неделя')),ButtonSegment(value:2,label:Text('Всё время'))],selected:{i},onSelectionChanged:(s)=>setState(()=>i=s.first)),Expanded(child:a.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Text('Ошибка: $e')),data:(items)=>RefreshIndicator(onRefresh:()async=>ref.refresh(topProvider(p).future),child:items.isEmpty?const Center(child:Text('Топ пока пуст')):ListView.builder(itemCount:items.length,itemBuilder:(c,n){final m=items[n];return ListTile(leading:Text('${m.position??n+1}'),title:Text(m.title),subtitle:Text('Рейтинг ${m.rating} · ${m.wins}/${m.losses}'),trailing:m.wins+m.losses>0?Text('${(m.wins*100/(m.wins+m.losses)).round()}%'):null);}))))]));}}
class UploadScreen extends ConsumerStatefulWidget{const UploadScreen({super.key});@override ConsumerState<UploadScreen> createState()=>_UploadScreenState();}class _UploadScreenState extends ConsumerState<UploadScreen>{final title=TextEditingController(),src=TextEditingController();String? path,msg;@override Widget build(c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Text('Загрузка мема'),OutlinedButton(onPressed:()async{final x=await ImagePicker().pickImage(source:ImageSource.gallery);if(x!=null)setState(()=>path=x.path);},child:Text(path==null?'Выбрать изображение':'Изображение выбрано')),if(path!=null)Padding(padding:const EdgeInsets.symmetric(vertical:12),child:Image.file(File(path!),height:180,fit:BoxFit.cover)),TextField(controller:title,decoration:const InputDecoration(labelText:'Название')),TextField(controller:src,decoration:const InputDecoration(labelText:'URL источника (необязательно)')),FilledButton(onPressed:path==null||title.text.trim().isEmpty?null:()async{final f=File(path!);final ext=path!.split('.').last.toLowerCase();if(!['jpg','jpeg','png','webp'].contains(ext)){setState(()=>msg='Поддерживаются JPEG, PNG и WebP');return;}if(await f.length()>10*1024*1024){setState(()=>msg='Файл слишком большой');return;}try{final id=ref.read(sessionProvider).value!;final media=await ref.read(repoProvider).upload(id,f);await ref.read(repoProvider).createMeme(id,title.text.trim(),media,src.text.trim());setState(()=>msg='Мем отправлен на модерацию');title.clear();src.clear();path=null;}catch(e){setState(()=>msg=e.toString());}},child:const Text('Отправить на модерацию')),if(msg!=null)Text(msg!)]));}
class ProfileScreen extends ConsumerWidget{const ProfileScreen({super.key});@override Widget build(c,ref){final id=ref.watch(sessionProvider).value!;final p=ref.watch(FutureProvider((r)=>r.watch(repoProvider).profile(id)));return SafeArea(child:p.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Text('Ошибка: $e')),data:(u)=>ListView(padding:const EdgeInsets.all(16),children:[Text(u.nickname,style:Theme.of(c).textTheme.headlineMedium),Text(statusLabel(u.status)),Text('Голосов: ${u.votesCount}'),Text('Мемов: ${u.submittedMemesCount}'),if(u.createdAt!=null)Text('Регистрация: ${u.createdAt}'),FilledButton(onPressed:()=>ref.invalidate(repoProvider),child:const Text('Обновить')),OutlinedButton(onPressed:()async{final ok=await showDialog<bool>(context:c,builder:(d)=>AlertDialog(title:const Text('Сменить пользователя?'),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Нет')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Да'))]));if(ok==true)ref.read(sessionProvider.notifier).logout();},child:const Text('Сменить пользователя'))])));}}
